
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cathaybk_demo
    username: postgres
  jpa:
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
        #format_sql: true
        show-sql: true
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        ddl-auto: create-drop
        jdbc:
          time_zone: GMT+8